FROM python:2.7

WORKDIR /home/ubuntu/

RUN wget https://raw.githubusercontent.com/scottdbrown/TCR-from-RNAseq2015/12a9778aa38fd07757cd6a8d3d33806e42431d76/combineAndCleanFastq.py

RUN chmod +x combineAndCleanFastq.py
